services:
  main:
    container_name: main
    build: .
    command: uvicorn src.uv_test_case.main:app --host 0.0.0.0
    ports:
      - 8000:8000
  cars:
    container_name: cars 
    build:
      context: src/cars
      dockerfile: ../../Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8001 
    ports:
      - 8001:8001
  cats:
    container_name: cats
    build:
      context: src/cats
      dockerfile: ../../Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    ports:
      - 8002:8002
  dogs:
    container_name: dogs 
    build:
      context: src/dogs
      dockerfile: ../../Dockerfile
    command: sanic main --host 0.0.0.0 --port 8003
    ports:
      - 8003:8003
