services:
  main:
    container_name: main
    build: .
    command: uvicorn src.uv_test_case.main:app --host 0.0.0.0 --reload
    ports:
      - 8000:8000
    environment:
      CARS_API: http://localhost:8001
      CATS_API: http://localhost:8002
      DOGS_API: http://localhost:8003
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
  cars:
    container_name: cars 
    build:
      context: src/cars
      dockerfile: ../../Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8001 
    ports:
      - 8001:8001
  cats:
    container_name: cats
    build:
      context: src/cats
      dockerfile: ../../Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    ports:
      - 8002:8002
  dogs:
    container_name: dogs 
    build:
      context: src/dogs
      dockerfile: ../../Dockerfile
    command: sanic main --host 0.0.0.0 --port 8003
    ports:
      - 8003:8003
