services:
  cars:
    container_name: cars 
    build:
      context: src/cars
      dockerfile: ../../Dockerfile
      args:
        APP_NAME: cars
    command: uvicorn src.cars.main:app --host 0.0.0.0 --port 8001 
    ports:
      - 8001:8001
  cats:
    container_name: cats
    build:
      context: src/cats
      dockerfile: ../../Dockerfile
      args:
        APP_NAME: cats
    command: quart run --host 0.0.0.0 --port 8002
    ports:
      - 8002:8002
    environment:
      QUART_APP: main:app
  dogs:
    container_name: dogs 
    build: .
  main:
    container_name: main
    build: .
